name: app
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^1.0.1
  rxdart: ^0.18.0
  http: ^0.12.0+2
  json_annotation: ^2.0.0
  flutter_html: ^0.10.4
  flutter_swiper: ^1.1.6
  cached_network_image: ^2.0.0-rc
  shared_preferences: ^0.5.7+3
  country_code_picker: ^1.1.7
  url_launcher: ^5.4.11
  timeago: ^2.0.26
  flutter_rating_bar: ^3.0.1+1
  webview_flutter: ^0.3.18+1
  font_awesome_flutter: ^8.5.0
  share: ^0.6.3+3
  place_picker: ^0.9.14
  location: 2.3.5
  fluttertoast: ^3.1.3
  flutter_paystack: 1.0.2+1
  sign_in_with_apple: ^2.5.2
  image_picker: ^0.6.6+4
  flutter_webview_plugin: 0.3.10+1
  smooth_star_rating: ^1.1.1
  flutter_icons: ^1.1.0
  firebase_auth: ^0.18.0+1
  google_sign_in: ^4.5.1
  flutter_facebook_login: ^3.0.0
  fab_circular_menu: ^0.1.4
  google_fonts: ^0.3.5
  stripe_payment: ^1.0.7
  network_to_file_image: ^2.3.1
  path_provider: ^1.4.4
  barcode_scan: ^2.0.0
#  barcode_scan_fix: ^1.0.2
  geocoder: ^0.2.1
  firebase_core: 0.5.0
  firebase_analytics: 6.0.0
  firebase_storage: 4.0.0
  cloud_firestore: 0.14.0+2
  photo_view: ^0.10.2
  intro_slider: ^2.3.1
  onesignal_flutter: ^2.6.1
  firebase_messaging: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.jpg"

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/
    - lib/assets/images/
    - lib/assets/images/intro/

  fonts:
    - family: MStoreIcons
      fonts:
        - asset: lib/assets/fonts/Icons/MStoreIcons.ttf